name: mouvema
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  cloud_firestore: ^4.8.4
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dot_navigation_bar: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.2.0
  flutter_search_bar: ^3.0.0-dev.1
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.1
  internet_connection_checker: ^1.0.0+1
  latlong2: ^0.9.0
  liquid_pull_to_refresh: ^3.0.1
  nominatim_geocoding: ^0.0.6
  pin_code_fields: ^8.0.1
  salomon_bottom_bar: ^3.3.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.12
  location: ^5.0.0
  carousel_slider: ^4.2.1
  fan_carousel_image_slider: any
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 500
