// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3C20lURKMYWCuzGwIHbxAhrHkOaWD84I',
    appId: '1:368796721209:web:1657924d69a5aef453ade8',
    messagingSenderId: '368796721209',
    projectId: 'startup-9945a',
    authDomain: 'startup-9945a.firebaseapp.com',
    storageBucket: 'startup-9945a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4rRItK2u5qqIb1Bby8zOiT1jmRX897k',
    appId: '1:368796721209:android:d8addf44328b844353ade8',
    messagingSenderId: '368796721209',
    projectId: 'startup-9945a',
    storageBucket: 'startup-9945a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCSUHG8bri0t23QIvotPUvo_IYgZLNAw',
    appId: '1:368796721209:ios:def0845232ae3e3b53ade8',
    messagingSenderId: '368796721209',
    projectId: 'startup-9945a',
    storageBucket: 'startup-9945a.appspot.com',
    iosClientId: '368796721209-mg7smdqil2nu9n4kgq22l7f3gc1n9f2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.doft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCSUHG8bri0t23QIvotPUvo_IYgZLNAw',
    appId: '1:368796721209:ios:f3f81a3aee61f83f53ade8',
    messagingSenderId: '368796721209',
    projectId: 'startup-9945a',
    storageBucket: 'startup-9945a.appspot.com',
    iosClientId: '368796721209-t54g776jrecnm6ab1fkjrnqudb0uh6bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.doft.RunnerTests',
  );
}
