List<Map<String, String>> loads = [
  {
    'loaddate': '6/12',
    'pickupdate': '20/6',
    'dropdowndate': '25/6',
    'trucktype': 'poid lourd',
    'broker': 'taher ',
    'telbroker': '97 285 362',
    'origin': 'nabeul',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '16/26',
    'pickupdate': '56/6',
    'dropdowndate': '26/15',
    'trucktype': 'stafett',
    'broker': 'hedi',
    'telbroker': '23654159',
    'origin': 'beja',
    'destination': 'gbeli',
    'price': '100',
    'weigth': '2500',
    'loadRef': '#254564654',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '12/06',
    'pickupdate': '12/5',
    'dropdowndate': '12/6',
    'trucktype': 'pick up',
    'broker': 'anis',
    'telbroker': '56235956',
    'origin': 'Gafsa',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '6/12',
    'pickupdate': '20/6',
    'dropdowndate': '25/6',
    'trucktype': 'poid lourd',
    'broker': 'taher ',
    'telbroker': '97 285 362',
    'origin': 'nabeul',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '16/26',
    'pickupdate': '56/6',
    'dropdowndate': '26/15',
    'trucktype': 'stafett',
    'broker': 'hedi',
    'telbroker': '23654159',
    'origin': 'beja',
    'destination': 'gbeli',
    'price': '100',
    'weigth': '2500',
    'loadRef': '#254564654',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '12/06',
    'pickupdate': '12/5',
    'dropdowndate': '12/6',
    'trucktype': 'pick up',
    'broker': 'anis',
    'telbroker': '56235956',
    'origin': 'Gafsa',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '6/12',
    'pickupdate': '20/6',
    'dropdowndate': '25/6',
    'trucktype': 'poid lourd',
    'broker': 'taher ',
    'telbroker': '97 285 362',
    'origin': 'nabeul',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '16/26',
    'pickupdate': '56/6',
    'dropdowndate': '26/15',
    'trucktype': 'stafett',
    'broker': 'hedi',
    'telbroker': '23654159',
    'origin': 'beja',
    'destination': 'gbeli',
    'price': '100',
    'weigth': '2500',
    'loadRef': '#254564654',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '12/06',
    'pickupdate': '12/5',
    'dropdowndate': '12/6',
    'trucktype': 'pick up',
    'broker': 'anis',
    'telbroker': '56235956',
    'origin': 'Gafsa',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '6/12',
    'pickupdate': '20/6',
    'dropdowndate': '25/6',
    'trucktype': 'poid lourd',
    'broker': 'taher ',
    'telbroker': '97 285 362',
    'origin': 'nabeul',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '16/26',
    'pickupdate': '56/6',
    'dropdowndate': '26/15',
    'trucktype': 'stafett',
    'broker': 'hedi',
    'telbroker': '23654159',
    'origin': 'beja',
    'destination': 'gbeli',
    'price': '100',
    'weigth': '2500',
    'loadRef': '#254564654',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
  {
    'loaddate': '12/06',
    'pickupdate': '12/5',
    'dropdowndate': '12/6',
    'trucktype': 'pick up',
    'broker': 'anis',
    'telbroker': '56235956',
    'origin': 'Gafsa',
    'destination': 'gbeli',
    'price': '100',
    'loadRef': '#254564654',
    'weigth': '2500',
    'description':
        'write me a description of the product and the price of the product and the price of the product ',
  },
];


